# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
          - id: markdownlint
    - repo: https://github.com/mrtazz/checkmake
      rev: 0.2.2
      hooks:
          - id: checkmake
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.23.2
      hooks:
          - id: check-github-workflows
    - repo: ssh://git@pinky:222/ralsina/pre-commit-hooks.git
      rev: 04cd8606213a6508e697b1f187c59cab16453ebd
      hooks:
          - id: ameba
